import { BookType } from "@/types";

export const books: BookType[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Classic",
    summary: "A story of the Jazz Age, a time of excess and illusion, and its tragic aftermath.",
    date: "1925-04-10",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    summary: "A novel that explores the irrationality of adult attitudes toward race and class in the Deep South of the 1930s.",
    date: "1960-07-11",
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    category: "Dystopian",
    summary: "A dystopian novel set in Airstrip One, a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation.",
    date: "1949-06-08",
  },
  {
    id: "4",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Coming-of-age",
    summary: "A story narrated by a young man who is undergoing treatment in a mental hospital, revealing his experiences and thoughts.",
    date: "1951-07-16",
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Romance",
    summary: "A novel exploring the themes of love, reputation, and class, revolving around the life of Elizabeth Bennet.",
    date: "1813-01-28",
  },
  {
    id: "6",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    summary: "The tale of Bilbo Baggins, a hobbit who is reluctantly swept into an epic quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug.",
    date: "1937-09-21",
  },
  {
    id: "7",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    category: "Fantasy",
    summary: "The first book in the Harry Potter series, following the journey of a young wizard, Harry Potter, as he attends Hogwarts School of Witchcraft and Wizardry.",
    date: "1997-06-26",
  },
  {
    id: "8",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    summary: "An epic high-fantasy novel that follows the quest to destroy the One Ring and defeat the Dark Lord Sauron.",
    date: "1954-07-29",
  },
  {
    id: "9",
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Dystopian",
    summary: "Set in a futuristic World State, where people are engineered and conditioned for a peaceful and conformist society.",
    date: "1932-10-27",
  },
  {
    id: "10",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Philosophical Fiction",
    summary: "A philosophical novel about Santiago, a young shepherd, and his journey to discover his personal legend and fulfill his destiny.",
    date: "1988-08-23",
  },
  {
    id: "11",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Mystery",
    summary: "A gripping mystery thriller that follows symbologist Robert Langdon as he investigates a murder at the Louvre Museum in Paris.",
    date: "2003-03-18",
  },
  {
    id: "12",
    title: "The Road",
    author: "Cormac McCarthy",
    category: "Post-apocalyptic",
    summary: "A post-apocalyptic novel that follows a father and his young son as they journey across a desolate and dangerous landscape.",
    date: "2006-09-26",
  },
];
